let routes=require("express");
let regCtrl=require("../controller/homepagectrl");
let router=routes.Router();
router.get("/",regCtrl.homepagectrl);
router.get("/login",regCtrl.login);
router.get("/signup",regCtrl.signup);
router.post("/register",regCtrl.regCtrl);
router.post("/validate",regCtrl.validate);
// router.post("/admindashboard",regCtrl.admindashboard);
// router.post("/userdshboard",regCtrl.userdashboard);
router.get("/hoteltab",regCtrl.hotelTab);
router.get("/citytab",regCtrl.cityTab);
router.get("/addcity",regCtrl.addcity);
router.post("/cityadd",regCtrl.cityAdd);
router.get("/showcity",regCtrl.showCity);
module.exports=router;